// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/gouez/gg-seq/app/internal/biz"
	"github.com/gouez/gg-seq/app/internal/conf"
	"github.com/gouez/gg-seq/app/internal/data"
	"github.com/gouez/gg-seq/app/internal/server"
	"github.com/gouez/gg-seq/app/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	seqRepo := data.NewSeqRepo(dataData, logger)
	seqUsecase := biz.NewSeqUsecase(seqRepo, logger)
	idGeneratorFactory := biz.NewIdGeneratorFactory(logger, seqUsecase)
	seqService := service.NewSeqService(seqUsecase, idGeneratorFactory, logger)
	httpServer := server.NewHTTPServer(confServer, seqService, logger)
	grpcServer := server.NewGRPCServer(confServer, seqService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
