// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.3

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type SeqHTTPServer interface {
	GetId(context.Context, *GetIdReq) (*GetIdResp, error)
}

func RegisterSeqHTTPServer(s *http.Server, srv SeqHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/getId/{biz_type}", _Seq_GetId0_HTTP_Handler(srv))
}

func _Seq_GetId0_HTTP_Handler(srv SeqHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetIdReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/seq.v1.Seq/GetId")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetId(ctx, req.(*GetIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetIdResp)
		return ctx.Result(200, reply)
	}
}

type SeqHTTPClient interface {
	GetId(ctx context.Context, req *GetIdReq, opts ...http.CallOption) (rsp *GetIdResp, err error)
}

type SeqHTTPClientImpl struct {
	cc *http.Client
}

func NewSeqHTTPClient(client *http.Client) SeqHTTPClient {
	return &SeqHTTPClientImpl{client}
}

func (c *SeqHTTPClientImpl) GetId(ctx context.Context, in *GetIdReq, opts ...http.CallOption) (*GetIdResp, error) {
	var out GetIdResp
	pattern := "/v1/getId/{biz_type}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/seq.v1.Seq/GetId"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
